### ISSUE TITLE
Work with screen off

### ISSUE THREAD

**Issue by lawson85** [Waboodoo/Status-Bar-Tachometer#14]
When my screen turns off the app stood putting the speed in my notification area

**Comment by Waboodoo** [comment]
This is intentional. Can you explain why you need the notifications when the screen is off?

**Comment by lawson85** [comment]
So that I can have it read to me by MacroDroid every x time when walking. At the moment I built a script to hold the screen on which is a huge battery drain

**Comment by Waboodoo** [comment]
There is now (as of version 2.3) an option to have the app keep updating the notification even when the screen is off.
