### ISSUE TITLE
Speedometer scale incorrect

### ISSUE THREAD

**Issue by PvdBerg1998** [Waboodoo/Status-Bar-Tachometer#15]
I've always used kmh, which works great. However when changing to the other scales for fun, I noticed none of them are displaying correctly. For example, my speed was 75 mph, but the speedometer was somewhere below 60 mph.

**Comment by rancid941** [comment]
- [ ] UDijebeg DX if 2[]()🤐~~```
🎃🉐bwl1🈳🈂🈹㊗◼```
```
- [ ] 😯🙁😭☹️😟https://user-images.githubusercontent.com/93974827/149512708-9addfda0-0603-477d-bed6-e909be707a70.mp4
```
```
```~~

**Comment by Waboodoo** [comment]
I can not proproduce this. I double-checked the conversion factor and it seems to be correct. Since I made some changes around how the speed is determined in version 3.6.0, this might now be completely fixed, so I'm closing this issue now.
