### ISSUE TITLE
Add the latest version to F-Droid and GitHub

### ISSUE THREAD

**Issue by Aga-C** [Waboodoo/Status-Bar-Tachometer#18]
Hi,
I've noticed that the latest version of the app is only in Google Play. Could you also add it to F-Droid and GitHub?
Thanks!

**Comment by Waboodoo** [comment]
Thanks for the reminder, I forgot about publishing it on Github. There is a new release now with the APK attached, and F-Droid should pick it up automatically within a few days as well.
