### ISSUE TITLE
[Feature Request] Add dark mode option

### ISSUE THREAD

**Issue by Aga-C** [Waboodoo/Status-Bar-Tachometer#19]
Hi,

I think it would be useful to add the possibility to switch between light and dark mode. A use case for this would be having the app running while riding the bike at night (phone strapped to the handlebars) - with white background it's blinding; dark background is more suitable in such case.

Thanks!

**Comment by Aga-C** [comment]
Thanks for adding this feature in the newest version!

**Comment by Waboodoo** [comment]
Oh wow, quick response. You're welcome. 👍🏻
