### ISSUE TITLE
Speedometer crashes before it will even display the speed

### ISSUE THREAD

**Issue by Josh-Reimer** [Waboodoo/Status-Bar-Tachometer#24]
Device:
Samsung Galay A5(2017)
Running Android Oreo

After the last update the Speedometer app displays a large question mark in the status bar and then crashes if I grant it the location permission. 

How to reproduce:
1. Make sure the app has location permission
2. Open the app
3. Enable the status bar notification
4. Wait for crash

**Comment by Waboodoo** [comment]
Thanks for the bug report.
It seems I have once again fallen for the "didn't carefully read the fine print warning in the documentation".
The bug is now fixed and a new version (3.5.1) will be available on the Play Store shortly.
