### ISSUE TITLE
Improve light theme

### ISSUE THREAD

**Issue by xmha97** [Waboodoo/Status-Bar-Tachometer#25]
Please add the light theme to all objects.

# Dark
![Screenshot_2022-11-19-22-32-06-049_ch.rmy.android.statusbar_tacho-02.jpeg](https://user-images.githubusercontent.com/23485114/202867416-74f71d01-b08a-4a43-9d0b-1e1993f25047.jpeg)

# Light
![Screenshot_2022-11-19-22-32-06-049_ch.rmy.android.statusbar_tacho-01.jpeg](https://user-images.githubusercontent.com/23485114/202867421-f5c19875-de8d-4f7d-8c77-577d96a3fc37.jpeg)

**Comment by Waboodoo** [comment]
The speed gauge component was styled like that on purpose. It looks the same in light and dark theme, because I think it works in both. If you disagree, could you elaborate?

**Comment by xmha97** [comment]
I prefer that the speed gauge component has a bright theme as well because bright components are more legible during the day, especially when the sun is shining directly on the phone.

**Comment by Waboodoo** [comment]
Alright. I'll add this the next time I work on this project. That might take a while though.

**Comment by xmha97** [comment]
Ok, thanks.

**Comment by Waboodoo** [comment]
So, it took quite a while for me to get back to this, but it's done now. As of version 3.6.0, which will go online soon, the speed gauge has a more distinct and more reasonable color scheme for dark and light mode.
