### ISSUE TITLE
Showing 0 when moving on Android 12

### ISSUE THREAD

**Issue by lawson85** [Waboodoo/Status-Bar-Tachometer#26]
**Describe the bug**
The app shows 0 even when moving
**To Reproduce**
1. Open app, enable it, see error

**Expected behavior**
Should show actual speed, in taxi or on foot

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 12
**Additional context**

**Comment by Waboodoo** [comment]
Thanks, I'll see what I can do.

**Comment by Waboodoo** [comment]
This might be fixed now in version 3.6.0, which is being released now.
