### ISSUE TITLE
Under access problem when using screen reader

### ISSUE THREAD

**Issue by zhou-zhoukang** [Waboodoo/Status-Bar-Tachometer#27]
**Device and app version**
- Device: Pixel 4
- OS: Android 13
- Status Bar Speedometer Version 3.8.0 

**Describe**
Thank you for the app. The clean UI design is quite appealing. There are some accessibility issues for those who have to use talkback(a screen reader) to navigate the app. In SettingsDialog, when tabbing the Pickers, talkback will tell you that it is an edit box, and that you can double-tab to edit it (in fact it is not editable) which may cause confusion. Furthermore, talkback just tell that the button to the right of the picker is a "button" when user tab it. The user is unaware of its actual function. More content descriptions may helps a lot.

**Screenshot**
![image](https://github.com/Waboodoo/Status-Bar-Tachometer/assets/75771822/60306d73-239d-4ab7-8291-82cae38ade5d)

**Comment by Waboodoo** [comment]
Thanks for bringing this to my attention. I made some small improvements to the accessibility now, which will be released soon as part of version 3.10.1.

**Comment by Waboodoo** [comment]
Closing this now as improvements have been made and released.
