### ISSUE TITLE
Add option to start the app on boot.

### ISSUE THREAD

**Issue by deavmi** [Waboodoo/Status-Bar-Tachometer#5]
Add option to start the app on boot.

**Comment by Waboodoo** [comment]
To me this seems like a feature that would be used by very few people. As such I have decided to not implement it at this point.

However, it is possible to start the app right after boot by triggering the app's home screen shortcuts through the use of an automation app such as [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) or [E-Robot](https://play.google.com/store/apps/details?id=com.bartat.android.robot) (you'll find those on the Play Store).

**Comment by gsosna** [comment]
Hi @Waboodoo there is at least one comment in the app feedback on google play about someone wanting this, plus me - I use your app on Android Car Stereo (PX5) - and having current speed in the status-bar automatically would be something I would appreciate. Please reconsider this feature request again.

**Comment by lawson85** [comment]
+1
